### ISSUE TITLE
Login - No Response

### ISSUE THREAD

**Issue by leiaaloha** [tonywagner/plugin.video.mlbserver#12]
after putting in username and password, get

redirects to /mlb/login
This page isn’t working x.x.x.x didn’t send any data.
ERR_EMPTY_RESPONSE

Can confirm the settings.xml does show my username and password after I try to login. from there nothing works. e.g. team lists shows, but won't play and if I just try to list today's games does not work. 

This was using docker compose

**Comment by tonywagner** [comment]
I just published a new version, make sure you are using that and let me know if the problem persists. [2024.7.24.1](https://hub.docker.com/layers/tonywagner/plugin.video.mlbserver/2024.7.24.1/images/sha256-68b053ed32649ae069eb041b0616c10534e80632a8784a4a284e529b5a613f75?context=repo)

**Comment by leiaaloha** [comment]
Docker won't stay running. 
fd5e5532621e   tonywagner/plugin.video.mlbserver:2024.7.24.1   "python3 service.py"   11 seconds ago   Restarting (0) Less than a second ago             plugin.video.mlbserver

**Comment by leiaaloha** [comment]
Also tried the :latest tag, but issue is the same on login

**Comment by leiaaloha** [comment]
Just tried, docker pull tonywagner/plugin.video.mlbserver:2024.7.24.1 that starts but same error

**Comment by tonywagner** [comment]
I suspect this should be fixed by https://github.com/tonywagner/plugin.video.mlbserver/commit/0082d833c1a67192a6618de2f16dd883ec900a97, if not earlier. Let me know if it's still a problem on the latest version.
