### ISSUE TITLE
new Issue when trying to view a game via m3u

### ISSUE THREAD

**Issue by SethL** [tonywagner/plugin.video.mlbserver#15]
Rebooting the container cleared it for a workaround. Not sure what happened before, sharing this with you in case there is a bigger issue going on etc

```
failed to get identify_stateHandle 'authenticators'

failed to get answer 'successWithInteractionCode'
```

**Comment by tonywagner** [comment]
Thanks. I think I have an idea of the problem and a solution for the next update.
