### ISSUE TITLE
Mlbserver doesnt keep login session after 24 hours

### ISSUE THREAD

**Issue by Timbo303** [tonywagner/plugin.video.mlbserver#16]
So I log in yesterday on the latest version. Works fine one day.

However after 24 hours or after a day the stream no longer loads unless you login everyday. Gives me EOF error on channelsdvr when trying to load the stream when it requires you to log out and login to fix.

**Comment by tonywagner** [comment]
Let me know if this problem continues with the latest version.

**Comment by tonywagner** [comment]
Still appears to be an issue. Will fix in next update.
