### ISSUE TITLE
mlb games won't play - errors in the logs 

### ISSUE THREAD

**Issue by SethL** [tonywagner/plugin.video.mlbserver#20]
[_new_mlb_server_logs.txt](https://github.com/user-attachments/files/16701066/_new_mlb_server_logs.txt)

same type issue as https://github.com/tonywagner/mlbserver/issues/52#issue-2479451492
Container doesn't die like mlbserver but it just errors out, logs attached

**Comment by SethL** [comment]
I got mlbserver working but the plugin container wont work at all.   The crazy thing is I see the container doing dns requests to mlb but there are zero items in the container log.  I deleted everything in the persistent storage and restarted the container.  I set it up and logged in and I see all of the games.  I try to open one of them and I just get a gray screen with a spinning wheel. Then I check the logs and there arent any.  I look at my DNS server (same one that mlbserver is using successfully) and I can see the DNS requests and everything looks normal.

On channels the logs only show me this:
`Could not start stream for M3U-mlbtvservernew ch1010 Dodgers: M3U: Could not fetch playlist from 192.168.12.41:5714: Get "http://192.168.12.41:5714/mlb/stream.m3u8?teamId=119&resolution=best": EOF`

I guess I can just quit using this and just use mlbserver, I just like the web front end you have for this one...

**Comment by tonywagner** [comment]
Still works for me.

Have you tried logging out and logging back in? That should clear your session. You could also nuke the container's data folder.

**Comment by SethL** [comment]
> Still works for me.
> 
> Have you tried logging out and logging back in? That should clear your session. You could also nuke the container's data folder.

OK so yeah I did that yesterday and it still failed.. I just gave up honestly.  Then I came back this afternoon and went into Channels and without thinking selected one of those channels and it just worked.  

Worst kind of IT issue I guess... One that just quits failing and works like it should with no intervention lol
