### ISSUE TITLE
Issue with xml

### ISSUE THREAD

**Issue by SethL** [tonywagner/plugin.video.mlbserver#21]
I'm trying to add this to channels dvr and I am getting some errors.  I rebooted the container and I can open the xml from my computer and it looks fine.  Once i add it to Channels I get an error and then I can no longer open the xml from any device.
`Failed to download XMLTV-mlbtvservernew: Get "http://192.168.12.41:5714/mlb/guide.xml": EOF`

I looked at the container logs and there appear to be some errors:
[_new_mlb_server_logs.txt](https://github.com/user-attachments/files/16966885/_new_mlb_server_logs.txt)

**Comment by tonywagner** [comment]
It was crashing on postseason placeholder games, since they don't have valid team IDs assigned yet.
