### ISSUE TITLE
Predictive m3u8 links?

### ISSUE THREAD

**Issue by charliebird** [tonywagner/plugin.video.mlbserver#9]
Hey @tonywagner 
Thanks a lot for all the work you're putting on this! 
I was a big user of mlbserver, and specifically used the predictive m3u8 URLs to automate my baseball viewing, are you working on adding that functionnality?

**Comment by tonywagner** [comment]
Basic predictive links work, just with teamId number instead of abbreviation string. See the Team Live Stream page for examples, and you can add "&date=yesterday" etc. to the URL.

**Comment by charliebird** [comment]
Thanks! Links are still only embed right? No straight m3u8?

**Comment by tonywagner** [comment]
> Thanks! Links are still only embed right? No straight m3u8?

No m3u8 listed in the web interface, but you can change any URL from "embed.html" to "stream.m3u8" to get you what you want.
